spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  session:
    store-type: none
